/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.xlogant.usuario;

import com.xlogant.acciones.accionaFormulario;
import com.xlogant.efecto.Explosion;
import com.xlogant.panel.PanelCrearUsuario;

import java.io.Serial;
import java.io.Serializable;
import javax.swing.JInternalFrame;

/**
 * @author oscar
 */
public final class CrearUsuario extends JInternalFrame implements Serializable {

    /**
     * Creates new form CrearUsuario
     */
    public CrearUsuario() {
        initComponents();
        Componentes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JPanel jPanel1 = new javax.swing.JPanel();
        cerrando = new javax.swing.JButton();
        panelContenedor = new javax.swing.JPanel();

        setTitle("Crear usuario");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        cerrando.setText("Cerrar");

        panelContenedor.setBackground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout panelContenedorLayout = new javax.swing.GroupLayout(panelContenedor);
        panelContenedor.setLayout(panelContenedorLayout);
        panelContenedorLayout.setHorizontalGroup(
                panelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 995, Short.MAX_VALUE)
        );
        panelContenedorLayout.setVerticalGroup(
                panelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(panelContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cerrando)
                                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(panelContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(cerrando)
                                .addGap(0, 524, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Componentes() {
        new Explosion(panelContenedor, new PanelCrearUsuario()).play();
        cerrando.addActionListener(e -> {
            this.dispose();
            accionaFormulario.elItem.setEnabled(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cerrando;
    private javax.swing.JPanel panelContenedor;
    // End of variables declaration//GEN-END:variables

    @Serial
    private static final long serialVersionUID = 5415833937668637289L;
}
