/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.xlogant.panel;

import com.xlogant.carga.CargaImagenUsuario;
import com.xlogant.principal.CentroPrincipal;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.Serial;
import java.util.Objects;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

import static com.xlogant.carga.CargaImagenUsuario.cargaImagenDB;
import static com.xlogant.carga.CargaImagenUsuario.cargaLaImagenDB;

/**
 *
 * @author oscar
 */
public class panelFoto extends javax.swing.JPanel {

    /**
     * Creates new form panelFoto
     */
    public panelFoto() {
        initComponents();
        muestraImagen();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        // Variables declaration - do not modify//GEN-BEGIN:variables
        javax.swing.JPanel contienelaFoto = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        setForeground(new java.awt.Color(153, 153, 0));
        setPreferredSize(new java.awt.Dimension(159, 188));
        setLayout(new java.awt.BorderLayout());

        contienelaFoto.setBackground(new java.awt.Color(255, 255, 255));
        contienelaFoto.setPreferredSize(new java.awt.Dimension(215, 252));

        javax.swing.GroupLayout contienelaFotoLayout = new javax.swing.GroupLayout(contienelaFoto);
        contienelaFoto.setLayout(contienelaFotoLayout);
        contienelaFotoLayout.setHorizontalGroup(
            contienelaFotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 155, Short.MAX_VALUE)
        );
        contienelaFotoLayout.setVerticalGroup(
            contienelaFotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 184, Short.MAX_VALUE)
        );

        add(contienelaFoto, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void muestraImagen() {
        var unID = CentroPrincipal.emas;
        var unNombre = CentroPrincipal.unNombre;
        JLabel etiqueta = new JLabel();
        ImageIcon controlImagenUsuario = cargaImagenDB(unID, unNombre);
        BufferedImage elbuffer = cargaLaImagenDB(unID, unNombre);
        PanelDibujaFoto dibujaFoto = new PanelDibujaFoto(elbuffer);
        if (elbuffer != null) {
            removeAll();
            add(dibujaFoto);
            elbuffer.flush();
            revalidate();
            repaint();
            updateUI();
        } else {
            ImageIcon iconos = new ImageIcon(Objects.requireNonNull(getClass().getResource("/com/xlogant/image/índice.png")));
            ImageIcon ico = new ImageIcon(iconos.getImage().getScaledInstance(215, 252, Image.SCALE_SMOOTH));
            etiqueta.setIcon(ico);
        }
        /*imagenRescalda = new ImageIcon(controlImagenUsuario.getImage().getScaledInstance(215, 252, Image.SCALE_DEFAULT));
         if (imagenRescalda != null) {
         etiqueta.setIcon(imagenRescalda);
         etiqueta.updateUI();
         etiqueta.revalidate();
         etiqueta.repaint();
         add(etiqueta);
         System.gc();
         Runtime.getRuntime().gc();
         System.runFinalization();
         } else {
         ImageIcon iconos = new ImageIcon(getClass().getResource("/com/xlogant/image/índice.png"));
         ImageIcon ico = new ImageIcon(iconos.getImage().getScaledInstance(215, 252, Image.SCALE_SMOOTH));
         etiqueta.setIcon(ico);
         System.gc();
         Runtime.getRuntime().gc();
         System.runFinalization();
         }*/
    }
    // End of variables declaration//GEN-END:variables

    @Serial
    private static final long serialVersionUID = 1023984337130252679L;
    private static ImageIcon imagenRescalda;
}
