/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.xlogant.sucursal;

import com.xlogant.acciones.accionaFormulario;
import com.xlogant.efecto.Explosion;
import com.xlogant.panel.PanelSucursal;

import javax.swing.JMenuItem;
import java.io.Serial;

/**
 * @author oscar
 */
public class CrearSucursal extends javax.swing.JInternalFrame {

    /**
     * Creates new form CrearSucursal
     */
    public CrearSucursal() {
        initComponents();
        elComponente();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cerrando = new javax.swing.JButton();
        elPanelSucursal = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));

        cerrando.setText("Cerrar");

        elPanelSucursal.setBackground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout elPanelSucursalLayout = new javax.swing.GroupLayout(elPanelSucursal);
        elPanelSucursal.setLayout(elPanelSucursalLayout);
        elPanelSucursalLayout.setHorizontalGroup(
                elPanelSucursalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 778, Short.MAX_VALUE)
        );
        elPanelSucursalLayout.setVerticalGroup(
                elPanelSucursalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(elPanelSucursal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cerrando)
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(cerrando)
                                .addContainerGap(363, Short.MAX_VALUE))
                        .addComponent(elPanelSucursal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void elComponente() {
        PanelSucursal panelDeSucursal = new PanelSucursal();
        new Explosion(elPanelSucursal, panelDeSucursal).play();
        cerrando.addActionListener(e -> {
            this.dispose();
            accionaFormulario.elItem.setEnabled(true);
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cerrando;
    private javax.swing.JPanel elPanelSucursal;
    // End of variables declaration//GEN-END:variables

    @Serial
    private static final long serialVersionUID = 6705991672189994241L;
}
