/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.xlogant.empresa;

import com.xlogant.acciones.accionaFormulario;
import com.xlogant.efecto.Explosion;
import com.xlogant.panel.EmpresaPanel;

import java.awt.*;
import java.io.Serial;

/**
 *
 * @author oscar
 */
public class CrearEmpresa extends javax.swing.JInternalFrame {

    /**
     * Creates new form CrearEmpresa
     */
    public CrearEmpresa() {
        initComponents();
        efectoPanelGUI();
    }

    private void efectoPanelGUI() {
        EmpresaPanel empresaPanel = new EmpresaPanel();
        new Explosion(contenedor, empresaPanel).play();
        termina.addActionListener(e -> {
            this.dispose();
            accionaFormulario.elItem.setEnabled(true);

        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JPanel jPanel3 = new javax.swing.JPanel();
        javax.swing.JLabel jLabel2 = new javax.swing.JLabel();
        termina = new javax.swing.JButton();
        contenedor = new javax.swing.JPanel();

        jPanel3.setLayout(new java.awt.BorderLayout());

        jLabel2.setFont(new java.awt.Font("Dialog", Font.BOLD, 48)); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel3.add(jLabel2, java.awt.BorderLayout.CENTER);

        setBackground(new java.awt.Color(255, 255, 255));

        termina.setText("Cerrar");

        contenedor.setBackground(new java.awt.Color(0, 153, 153));

        javax.swing.GroupLayout contenedorLayout = new javax.swing.GroupLayout(contenedor);
        contenedor.setLayout(contenedorLayout);
        contenedorLayout.setHorizontalGroup(
            contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 815, Short.MAX_VALUE)
        );
        contenedorLayout.setVerticalGroup(
            contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 473, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(contenedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(termina)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(termina)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel contenedor;
    private javax.swing.JButton termina;
    // End of variables declaration//GEN-END:variables
    @Serial
    private static final long serialVersionUID = 6663300234179839436L;
}
