/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.xlogant.principal;

import com.xlogant.controlador.ControlDeMenu;
import com.xlogant.desktop.FondoDesktop;
import com.xlogant.efecto.Explosion;
import com.xlogant.login.LoginDialog;
import com.xlogant.panel.PanelDibujaFoto;
import com.xlogant.usuario.CrearUsuario;

import java.awt.*;
import java.awt.event.ActionListener;
import java.io.Serial;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JMenu;
import javax.swing.JMenuItem;

import static com.xlogant.controlador.ControlCerrar.*;
import static java.awt.Toolkit.*;
import static java.lang.System.exit;
import static java.lang.System.out;
import static java.time.LocalTime.*;
import static java.time.format.DateTimeFormatter.*;
import static java.util.Locale.forLanguageTag;
import static javax.swing.JOptionPane.*;
import static javax.swing.SwingUtilities.updateComponentTreeUI;
import static javax.swing.UIManager.*;
import javax.swing.UnsupportedLookAndFeelException;
import com.xlogant.panel.panelFoto;

import java.awt.image.BufferedImage;
import javax.swing.UIManager;

/**
 *
 * @author oscar
 */
public final class CentroPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form CentroPrincipal
     */
    public CentroPrincipal() {
        initComponents();
        IniciaReloj();
        cargaVariables();
        cargaValores();
        cargaTemas();
        cargaLaImagenPanel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cerrado = new javax.swing.JButton();
        controlVariable = new javax.swing.JLabel();
        valorTexto = new javax.swing.JTextField();
        muestra = new javax.swing.JButton();
        org.jdesktop.swingx.JXStatusBar jXStatusBar2 = new org.jdesktop.swingx.JXStatusBar();
        javax.swing.JPanel jPanel1 = new javax.swing.JPanel();
        fechaSistema = new javax.swing.JLabel();
        laHora = new javax.swing.JLabel();
        panelContenedor = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        daNombre = new javax.swing.JLabel();
        enviavalores = new javax.swing.JLabel();
        javax.swing.JLabel etiquetaSucursal = new javax.swing.JLabel();
        elNombreSucursal = new javax.swing.JLabel();
        UIManager.put("MenuBar.background", Color.WHITE);
        UIManager.put("MenuItem.background", Color.WHITE);
        UIManager.put("MenuItem.opaque", true);
        barraMenu = new javax.swing.JMenuBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setLocationByPlatform(true);
        setUndecorated(true);

        cerrado.setText("Cerrar");

        controlVariable.setForeground(new java.awt.Color(51, 51, 255));

        valorTexto.setEditable(false);
        valorTexto.setForeground(new java.awt.Color(0, 51, 204));

        muestra.setText("Muestra");

        fechaSistema.setText("Fecha");

        laHora.setFont(new java.awt.Font("Dialog", Font.BOLD, 14)); // NOI18N
        laHora.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        laHora.setText("hora");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(435, Short.MAX_VALUE)
                .addComponent(fechaSistema)
                .addGap(56, 56, 56)
                .addComponent(laHora, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fechaSistema, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(laHora))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jXStatusBar2.add(jPanel1);

        panelContenedor.setBackground(new java.awt.Color(0, 102, 102));
        panelContenedor.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, new java.awt.Color(102, 0, 0)), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED)));
        panelContenedor.setPreferredSize(new java.awt.Dimension(215, 252));

        javax.swing.GroupLayout panelContenedorLayout = new javax.swing.GroupLayout(panelContenedor);
        panelContenedor.setLayout(panelContenedorLayout);
        panelContenedorLayout.setHorizontalGroup(
            panelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 205, Short.MAX_VALUE)
        );
        panelContenedorLayout.setVerticalGroup(
            panelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 242, Short.MAX_VALUE)
        );

        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setText("Usuario: ");

        daNombre.setForeground(new java.awt.Color(51, 51, 255));
        daNombre.setText("elNombre");

        etiquetaSucursal.setForeground(new java.awt.Color(51, 51, 255));
        etiquetaSucursal.setText("Sucursal: ");

        elNombreSucursal.setForeground(new java.awt.Color(51, 51, 255));
        elNombreSucursal.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        jDesktopPane1.setLayer(cerrado, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(controlVariable, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(valorTexto, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(muestra, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jXStatusBar2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(panelContenedor, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(daNombre, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(enviavalores, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(etiquetaSucursal, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(elNombreSucursal, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(enviavalores, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jXStatusBar2, javax.swing.GroupLayout.DEFAULT_SIZE, 793, Short.MAX_VALUE)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(controlVariable, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(muestra))
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(cerrado))
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(valorTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelContenedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jDesktopPane1Layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(daNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jDesktopPane1Layout.createSequentialGroup()
                            .addComponent(etiquetaSucursal)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(elNombreSucursal, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(controlVariable, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(muestra)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cerrado)
                .addGap(18, 18, 18)
                .addComponent(valorTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(enviavalores, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 363, Short.MAX_VALUE)
                .addComponent(jXStatusBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(daNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(etiquetaSucursal)
                    .addComponent(elNombreSucursal, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelContenedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jDesktopPane1, java.awt.BorderLayout.CENTER);
        setJMenuBar(barraMenu);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    private void cargaVariables() {
        mas = LoginDialog.jk;
        emas = LoginDialog.e_id;
        unNombre = LoginDialog.elNombre;
        IDEMPRE = LoginDialog.idempre;
        BaseNombreSuc = LoginDialog.nomSucursales;
    }

    private void cargaValores() {
       
        controlVariable.setVisible(false);
        valorTexto.setVisible(false);
        elNombreSucursal.setText(BaseNombreSuc);
        var mexico = forLanguageTag("es-MX");
        var anio = "dd/MM/yyyy";
        var tiempo = now();
        var valorFecha = LocalDate.now().format(ofPattern(anio, mexico));
        daNombre.setText(unNombre);
        fechaSistema.setText(valorFecha);
        jDesktopPane1.setBorder(new FondoDesktop());
        temas = new JMenu("Estilo");
        JMenu controlMenu = new JMenu();
        JMenuItem subItemsMenu = new JMenuItem();
        var roles = Long.valueOf(mas);
        var enviado = Long.valueOf(emas);
        ControlDeMenu.obtenerMenus(enviado, roles, true, jDesktopPane1, barraMenu, controlMenu, subItemsMenu);
        barraMenu.add(controlMenu);
        controlMenu.add(subItemsMenu);
        barraMenu.add(temas);
        revalidate();
        repaint();
        muestra.addActionListener(e -> {
            creandoUsuario = null;
            out.println("Dialogo destruido");
            var g = (creandoUsuario == null);
            out.println("Cerrado correctamente " + g);
            if (g && creandoUsuario == null) {
                creandoUsuario = new CrearUsuario();
                var pantalla = getDefaultToolkit().getScreenSize();
                var ventana = creandoUsuario.getSize();
                var x = ((pantalla.width - ventana.width) / 2);
                var y = ((pantalla.height - ventana.height) / 2);
                creandoUsuario.setLocation(x, y);
                creandoUsuario.setVisible(true);
                jDesktopPane1.add(creandoUsuario);
                var control = controlVariable.getText();
                showMessageDialog(this, control);
            }
        });
        /*Toolkit tk = Toolkit.getDefaultToolkit();
         int xSize = ((int) tk.getScreenSize().getWidth());
         int ySize = ((int) tk.getScreenSize().getHeight());
         setSize(new Dimension(xSize, ySize));*/
        cerrado.addActionListener(e -> {
            var close = showInternalConfirmDialog(jDesktopPane1, "Desea cerrar la aplicación", "Monitor", YES_NO_OPTION);
            if (close == YES_OPTION) {
                terminado = registraSalida(enviado, roles);
                if (terminado) {
                    out.println("Control de aplicaciones terminado");
                    //new Dissolver().dissolveExit(this);
                    exit(0);
                } else {
                    out.println("No se guardo la salida");
                    exit(0);
                }
            } else {
                showInternalMessageDialog(jDesktopPane1, "Cancelado salida del programa", "Monitor", INFORMATION_MESSAGE);
            }
        });
    }

    private void cargaTemas() {
        for (var info : getInstalledLookAndFeels()) {
            var nombreTema = info.getName();
            var nombreClase = info.getClassName();
            JMenuItem itemTema = new JMenuItem(nombreTema);
            temas.add(itemTema);
            temas.addSeparator();
            itemTema.addActionListener(e -> {
                try {
                    var nombre = e.getActionCommand();
                    if (nombreTema.equals(nombre)) {
                        setLookAndFeel(nombreClase);
                        updateComponentTreeUI(this);
                        out.println(nombre);
                    }
                } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
                    Logger.getLogger(CentroPrincipal.class.getName()).log(Level.SEVERE, null, ex);
                    out.println(ex.getLocalizedMessage());
                }
            });
        }
    }

    private void IniciaReloj() {
        ActionListener al = (e) -> cargarHoraLocal();
        javax.swing.Timer eltime = new javax.swing.Timer(1000, al);
        eltime.start();
    }

    private void cargarHoraLocal() {
        var tie = now();
        DateTimeFormatter fmts = ofPattern("KK:mm:ss a");
        Horas = fmts.format(tie);
        laHora.setText(Horas);
    }

    private void cargaLaImagenPanel() {
        panelFotografia = new panelFoto();
        new Explosion(panelContenedor, panelFotografia).play();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar barraMenu;
    public javax.swing.JButton cerrado;
    public static javax.swing.JLabel controlVariable;
    public static javax.swing.JLabel daNombre;
    public static javax.swing.JLabel elNombreSucursal;
    public static javax.swing.JLabel enviavalores;
    private javax.swing.JLabel fechaSistema;
    public static final javax.swing.JDesktopPane jDesktopPane1 = new javax.swing.JDesktopPane();
    public static javax.swing.JLabel jLabel1;
    private javax.swing.JLabel laHora;
    private javax.swing.JButton muestra;
    private javax.swing.JPanel panelContenedor;
    public static javax.swing.JTextField valorTexto;
    // End of variables declaration//GEN-END:variables
    
    @Serial private static final long serialVersionUID = 5756461516585461814L;
    public static String mas, emas,Horas;
    public static String unNombre;
    public static String ElNombre, BaseNombreSuc;
    public static long IDEMPRE;
    private JMenu temas;
    private CrearUsuario creandoUsuario;
    private boolean terminado;
    public static panelFoto panelFotografia;
    private static BufferedImage controlImagenUsuario;
    private static PanelDibujaFoto dibujaFoto;
}
