/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.xlogant.representante;

import com.xlogant.acciones.accionaFormulario;
import com.xlogant.efecto.Explosion;
import com.xlogant.panel.panelRepresentante;

import java.io.Serial;

/**
 * @author oscar
 */
public class CrearRepresentante extends javax.swing.JInternalFrame {


    /**
     * Creates new form CrearRepresentante
     */
    public CrearRepresentante() {
        initComponents();
        Componentes();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelexp = new javax.swing.JPanel();
        cerrando = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setTitle("Crear Representante");

        panelexp.setBackground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout panelexpLayout = new javax.swing.GroupLayout(panelexp);
        panelexp.setLayout(panelexpLayout);
        panelexpLayout.setHorizontalGroup(
                panelexpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 950, Short.MAX_VALUE)
        );
        panelexpLayout.setVerticalGroup(
                panelexpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE)
        );

        cerrando.setText("Cerrar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(panelexp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cerrando)
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(cerrando)
                                .addContainerGap(396, Short.MAX_VALUE))
                        .addComponent(panelexp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Componentes() {
        panelRepresentante panelrepre = new panelRepresentante();
        new Explosion(panelexp, panelrepre).play();
        cerrando.addActionListener(e -> {
            this.dispose();
            accionaFormulario.elItem.setEnabled(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cerrando;
    private javax.swing.JPanel panelexp;
    // End of variables declaration//GEN-END:variables

    @Serial
    private static final long serialVersionUID = 3277446196342586543L;
}
