/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.xlogant.login;

import com.xlogant.control.texto.JTextFieldLimit;
import com.xlogant.principal.CentroPrincipal;

import java.awt.*;
import java.awt.event.WindowAdapter;
import java.io.IOException;
import java.io.Serial;
import java.net.InetAddress;
import java.net.UnknownHostException;
import java.time.LocalDate;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;

import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;

import static java.lang.System.exit;
import static java.lang.System.out;

/**
 *
 * @author oscar
 */
public final class LoginDialog extends JDialog {

    private final AuthenticationService authService;
    private javax.swing.Timer clockTimer;

    /**
     * Creates new form LoginDialog
     *
     * @param parent
     * @param modal
     */
    public LoginDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        this.authService = new AuthenticationService();
        initComponents();
        initCustomComponents();
        startClock();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        javax.swing.JPanel jPanel1 = new javax.swing.JPanel();
        cerrar = new javax.swing.JButton();
        acceder = new javax.swing.JButton();
        javax.swing.JLabel jLabel1 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel2 = new javax.swing.JLabel();
        textNombre = new javax.swing.JTextField();
        textClave = new javax.swing.JPasswordField();
        teclado = new javax.swing.JButton();
        res = new javax.swing.JLabel();
        lajava = new javax.swing.JLabel();
        fechas = new javax.swing.JLabel();
        lahora = new javax.swing.JLabel();
        ip = new javax.swing.JLabel();
        sistema = new javax.swing.JLabel();
        javax.swing.JLabel tiempouso = new javax.swing.JLabel();
        psql = new javax.swing.JLabel();
        muestra = new javax.swing.JLabel();
        so = new javax.swing.JLabel();
        kernel = new javax.swing.JLabel();
        javax.swing.JLabel mas = new javax.swing.JLabel();
        javax.swing.JLabel jLabel3 = new javax.swing.JLabel();
        numProcesador = new javax.swing.JLabel();
        javax.swing.JLabel jLabel4 = new javax.swing.JLabel();
        vendorJava = new javax.swing.JLabel();
        so_user = new javax.swing.JLabel();
        javax.swing.JLabel jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Control de usuario");
        setModal(true);
        setModalExclusionType(java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        cerrar.setForeground(new java.awt.Color(204, 102, 0));
        cerrar.setText("Cerrar");

        acceder.setForeground(new java.awt.Color(204, 102, 0));
        acceder.setText("Acceder");

        jLabel1.setFont(new java.awt.Font("Dialog", Font.BOLD, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 102, 0));
        jLabel1.setText("Nombre de usuario: ");

        jLabel2.setFont(new java.awt.Font("Dialog", Font.BOLD, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 102, 0));
        jLabel2.setText("Clave de usuario: ");

        textNombre.setDocument(new JTextFieldLimit(18, false));
        textNombre.setFont(new java.awt.Font("Dialog", Font.BOLD, 14)); // NOI18N
        textNombre.setForeground(new java.awt.Color(255, 102, 0));
        textNombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textNombre.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 1, new java.awt.Color(204, 102, 0)));

        textClave.setDocument(new JTextFieldLimit(14, false));
        textClave.setFont(new java.awt.Font("Dialog", Font.BOLD, 14)); // NOI18N
        textClave.setForeground(new java.awt.Color(255, 102, 0));
        textClave.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textClave.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 1, new java.awt.Color(204, 102, 0)));

        teclado.setBackground(new java.awt.Color(255, 102, 0));

        res.setForeground(new java.awt.Color(204, 102, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(2, 2, 2))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(teclado, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addGap(1, 1, 1)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 314, Short.MAX_VALUE)
                            .addComponent(textClave))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(res, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(acceder)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cerrar)
                                .addGap(24, 24, 24)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(acceder)
                            .addComponent(cerrar)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(res, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(textNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(textClave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addComponent(teclado, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29))
        );

        lajava.setForeground(new java.awt.Color(255, 102, 0));
        lajava.setText("version de java");

        fechas.setFont(new java.awt.Font("Dialog", Font.BOLD, 70)); // NOI18N
        fechas.setForeground(new java.awt.Color(255, 153, 0));
        fechas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fechas.setText("fecha");

        lahora.setFont(new java.awt.Font("Dialog", Font.BOLD, 70)); // NOI18N
        lahora.setForeground(new java.awt.Color(255, 153, 0));
        lahora.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lahora.setText("Hora");

        ip.setForeground(new java.awt.Color(255, 153, 0));
        ip.setText("ip");

        sistema.setFont(new java.awt.Font("Dialog", Font.BOLD, 36)); // NOI18N
        sistema.setForeground(new java.awt.Color(255, 153, 0));
        sistema.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sistema.setText("Nombre SO");

        tiempouso.setForeground(new java.awt.Color(204, 102, 0));
        tiempouso.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tiempouso.setText("Tiempo de uso de la pc");

        psql.setForeground(new java.awt.Color(255, 102, 0));
        psql.setText("Versión de postgresql");

        muestra.setForeground(new java.awt.Color(255, 153, 0));
        muestra.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        so.setForeground(new java.awt.Color(255, 153, 0));
        so.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        so.setText("SO");

        kernel.setForeground(new java.awt.Color(255, 153, 0));
        kernel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        kernel.setText("kernel");

        mas.setForeground(new java.awt.Color(255, 102, 0));

        jLabel3.setForeground(new java.awt.Color(255, 153, 0));
        jLabel3.setText("Número de procesadores:");

        numProcesador.setForeground(new java.awt.Color(255, 153, 0));
        numProcesador.setText("0");

        jLabel4.setForeground(new java.awt.Color(255, 102, 0));
        jLabel4.setText("Versión de java: ");

        vendorJava.setForeground(new java.awt.Color(255, 102, 0));
        vendorJava.setText("vendor");

        so_user.setForeground(new java.awt.Color(255, 153, 0));

        jLabel5.setForeground(new java.awt.Color(255, 153, 0));
        jLabel5.setText("Usuario pc:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(muestra, javax.swing.GroupLayout.PREFERRED_SIZE, 536, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addGap(188, 188, 188)
                            .addComponent(ip, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(so, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(kernel, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fechas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(sistema, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addComponent(lahora, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(psql, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(mas, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(numProcesador, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(so_user, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(vendorJava, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lajava))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 287, Short.MAX_VALUE)
                .addComponent(tiempouso, javax.swing.GroupLayout.PREFERRED_SIZE, 547, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(446, 446, 446))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(292, 292, 292)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(fechas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lahora, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(kernel)
                            .addComponent(so)
                            .addComponent(ip, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(muestra, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(sistema, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tiempouso, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lajava)
                    .addComponent(psql)
                    .addComponent(jLabel3)
                    .addComponent(numProcesador)
                    .addComponent(jLabel4))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(mas, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(so_user, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(vendorJava)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE))))
                .addGap(30, 30, 30))
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(1298, 706));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void initCustomComponents() {
        // Configurar listeners y estado inicial de la UI
        setupSystemInfo();
        setupActionListeners();
        setupFocusTransfer();

        // Configurar la ventana para pantalla completa
        GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
        GraphicsDevice gd = ge.getDefaultScreenDevice();
        if (gd.isFullScreenSupported()) {
            setUndecorated(true);
            gd.setFullScreenWindow(this);
        } else {
            // Fallback para entornos que no soportan pantalla completa
            setExtendedState(JFrame.MAXIMIZED_BOTH);
            setUndecorated(true);
            setVisible(true);
        }
    }

    private void setupFocusTransfer() {
        textNombre.addActionListener(e -> textClave.requestFocusInWindow());
        textClave.addActionListener(e -> acceder.requestFocusInWindow());
    }

    private void setupSystemInfo() {
        so_user.setText(System.getProperty("user.name", "N/A"));
        sistema.setText(System.getProperty("os.name", "N/A"));
        kernel.setText(System.getProperty("os.version", "N/A"));
        lajava.setText(System.getProperty("java.version", "N/A"));
        vendorJava.setText(System.getProperty("java.vendor", "N/A"));
        numProcesador.setText(String.valueOf(Runtime.getRuntime().availableProcessors()));

        try {
            ip.setText(InetAddress.getLocalHost().getHostAddress());
        } catch (UnknownHostException e) {
            ip.setText("?.?.?.?");
            Logger.getLogger(LoginDialog.class.getName()).log(Level.WARNING, "No se pudo obtener la IP local", e);
        }
    }

    private void setupActionListeners() {
        acceder.addActionListener(e -> handleLogin());
        cerrar.addActionListener(e -> handleClose());
        teclado.addActionListener(e -> launchOnScreenKeyboard());

        acceder.setMnemonic('A');
        cerrar.setMnemonic('C');
        getRootPane().setDefaultButton(acceder);
    }

    private void handleLogin() {
        String username = textNombre.getText();
        String password = new String(textClave.getPassword());

        if (username.isBlank()) {
            showError("El campo usuario no puede estar vacío.", textNombre);
            return;
        }
        if (password.isBlank()) {
            showError("El campo clave no puede estar vacío.", textClave);
            return;
        }

        // Deshabilitar UI mientras se procesa
        setUIEnabled(false);
        res.setText("Autenticando, por favor espere...");

        // Usar SwingWorker para no bloquear la UI
        new SwingWorker<Optional<UsuarioDTO>, Void>() {
            @Override
            protected Optional<UsuarioDTO> doInBackground() {
                return authService.authenticate(username, password);
            }

            @Override
            protected void done() {
                try {
                    Optional<UsuarioDTO> result = get();
                    if (result.isPresent()) {
                        launchMainApplication(result.get());
                    } else {
                        showError("Usuario o clave incorrectos, o el usuario está inactivo.", textNombre);
                        resetLoginForm();
                    }
                } catch (Exception e) {
                    Logger.getLogger(LoginDialog.class.getName()).log(Level.SEVERE, "Error durante el login", e);
                    showError("Ocurrió un error inesperado durante el inicio de sesión.", textNombre);
                    resetLoginForm();
                } finally {
                    setUIEnabled(true);
                }
            }
        }.execute();
    }

    private void launchMainApplication(UsuarioDTO usuario) {
        // Detener timers y liberar recursos de esta ventana
        if (clockTimer != null) {
            clockTimer.stop();
        }
        dispose();

        // Lanzar la ventana principal, pasando el DTO del usuario
        EventQueue.invokeLater(() -> {
            CentroPrincipal centroPrincipal = new CentroPrincipal(usuario);
            centroPrincipal.setVisible(true);
        });
    }

    private void handleClose() {
        int choice = JOptionPane.showConfirmDialog(this,
                "¿Desea cerrar la aplicación?", "Confirmar Salida",
                JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);

        if (choice == JOptionPane.YES_OPTION) {
            exit(0);
        }
    }

    private void launchOnScreenKeyboard() {
        try {
            // Este comando es específico de Linux. En una app real, esto necesitaría
            // ser más robusto y multiplataforma.
            new ProcessBuilder("florence").start();
        } catch (IOException ex) {
            Logger.getLogger(LoginDialog.class.getName()).log(Level.WARNING, "No se pudo iniciar el teclado en pantalla 'florence'", ex);
            JOptionPane.showMessageDialog(this,
                    "No se pudo encontrar el teclado en pantalla (florence).\nAsegúrese de que esté instalado.",
                    "Error", JOptionPane.WARNING_MESSAGE);
        }
    }

    private void startClock() {
        // Usar javax.swing.Timer para seguridad con hilos de Swing
        clockTimer = new javax.swing.Timer(1000, e -> updateDateTime());
        clockTimer.setInitialDelay(0);
        clockTimer.start();
    }

    private void updateDateTime() {
        Locale mexicoLocale = new Locale("es", "MX");
        fechas.setText(LocalDate.now().format(DateTimeFormatter.ofPattern("dd/MM/yyyy", mexicoLocale)));
        lahora.setText(LocalTime.now().format(DateTimeFormatter.ofPattern("hh:mm:ss a")));
    }

    private void setUIEnabled(boolean enabled) {
        acceder.setEnabled(enabled);
        cerrar.setEnabled(enabled);
        textNombre.setEnabled(enabled);
        textClave.setEnabled(enabled);
    }

    private void resetLoginForm() {
        res.setText("Por favor, intente de nuevo.");
        textClave.setText("");
        textNombre.selectAll();
        textNombre.requestFocusInWindow();
    }

    private void showError(String message, JComponent componentToFocus) {
        JOptionPane.showMessageDialog(this, message, "Error de Autenticación", JOptionPane.ERROR_MESSAGE);
        if (componentToFocus != null) {
            componentToFocus.requestFocusInWindow();
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String... args) {
        try {
            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception ex) {
            Logger.getLogger(LoginDialog.class.getName()).log(Level.SEVERE, "No se pudo establecer el Look and Feel 'Metal'", ex);
        }

        EventQueue.invokeLater(() -> {
            var dialog = new LoginDialog(new JFrame(), true);
            dialog.addWindowListener(new WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton acceder;
    public javax.swing.JButton cerrar;
    private javax.swing.JLabel fechas;
    private javax.swing.JLabel ip;
    public javax.swing.JPanel jPanel2;
    private javax.swing.JLabel kernel;
    private javax.swing.JLabel lahora;
    private javax.swing.JLabel lajava;
    private javax.swing.JLabel muestra;
    private javax.swing.JLabel numProcesador;
    private javax.swing.JLabel psql;
    private javax.swing.JLabel res;
    private javax.swing.JLabel sistema;
    private javax.swing.JLabel so;
    private javax.swing.JLabel so_user;
    private javax.swing.JButton teclado;
    private javax.swing.JPasswordField textClave;
    private javax.swing.JTextField textNombre;
    private javax.swing.JLabel vendorJava;
    // End of variables declaration//GEN-END:variables
    @Serial
    private static final long serialVersionUID = -4477681729100140273L;
}
